version: "3.9"
networks:
  public:
  private:
volumes:
  db-data:
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment: # Will be set through .env file
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on: [db]
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    ports:
      - 6060:80
    networks:
      - private
  bot:
    build: . # During dev
    # image: dhananjaipai/coc-bot:latest
    depends_on: [db]
    container_name: bot
    environment: # Will be set through .env file
      - DATABASE_HOST=db
      - CLASH_API_TOKEN
      - NGROK_TOKEN
      - TELEGRAM_TOKEN
      - CHAT_ID
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_NAME
    ports:
      - 3000:3000
    # restart: unless-stopped
    networks:
      - public
      - private
